apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: k8s-cicd-app-base

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- pdb.yaml

labels:
- includeSelectors: true
  pairs:
    app: k8s-cicd-app
    managed-by: argocd
