name: GitOps Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-manifests:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2
    
    - name: Setup kubeval
      run: |
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo cp kubeval /usr/local/bin

    - name: Download Kubernetes Schemas
      run: |
        git clone --depth 1 https://github.com/yannh/kubernetes-json-schema.git schemas

    - name: Validate Development Environment
      run: |
        echo "Validating development environment manifests..."
        kustomize build applications/k8s-cicd-app/overlays/development | \
        kubeval --schema-location=file://$(pwd)/schemas --kubernetes-version="1.34.0"

    - name: Validate Staging Environment
      run: |
        echo "Validating staging environment manifests..."
        kustomize build applications/k8s-cicd-app/overlays/staging | \
        kubeval --schema-location=file://$(pwd)/schemas --kubernetes-version="1.34.0"

    - name: Validate Production Environment
      run: |
        echo "Validating production environment manifests..."
        kustomize build applications/k8s-cicd-app/overlays/production | \
        kubeval --schema-location=file://$(pwd)/schemas --kubernetes-version="1.34.0"

    - name: Check ArgoCD Applications
      run: |
        echo "Validating ArgoCD application manifests..."
        # Add --validate=false to disable validation
        argocd app validate argocd/applications/ --validate=false

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2
    
    - name: Run kube-score
      run: |
        wget https://github.com/zegl/kube-score/releases/download/v1.20.0/kube-score_1.20.0_linux_amd64.tar.gz
        tar xzf kube-score_1.20.0_linux_amd64.tar.gz
        sudo mv kube-score /usr/local/bin/
        
        echo "Scanning development manifests..."
        kustomize build applications/k8s-cicd-app/overlays/development | kube-score score -
        
        echo "Scanning staging manifests..."
        kustomize build applications/k8s-cicd-app/overlays/staging | kube-score score -
        
        echo "Scanning production manifests..."
        kustomize build applications/k8s-cicd-app/overlays/production | kube-score score -
